service: noggleboggle-rest

provider:
  name: aws
  runtime: nodejs12.x

functions:
  setupUser:
    handler: ./src/handlers/registration.setupUser
    events:
      - http:
          path: registration/setup
          method: post
          cors: false
  getUser:
    handler: ./src/handlers/users.getUser
    events:
      - http:
          path: users/user
          method: get
          cors: false
  getEventsForUser:
    handler: ./src/handlers/events.getEventsForUser
    events:
      - http:
          path: events/user
          method: get
          cors: false
